name: Docker

on: [push]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          severity: error

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build docker image
        run: |
          docker build . --tag ghcr.io/anyau/devops-task2:latest
          docker run ghcr.io/anyau/devops-task2:latest
          docker push ghcr.io/anyau/devops-task2:latest
